# Generated by Django 3.2.19 on 2023-07-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvdm', '0004_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='stripe_payment_intent',
        ),
    ]
