# Generated by Django 3.2.19 on 2023-07-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvdm', '0006_auto_20230727_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='customer_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
